### ISSUE TITLE
Invalid runtime error when deploying from cloudbuild

### ISSUE THREAD

**Issue by dpinart-uxland** [GoogleCloudPlatform/functions-framework-dotnet#175]
Hi

I'm trying to deply a cloud function using a clouduild triger. I have a repo with several projects and the cloud function is in a subfolder.

My cloudbuild.xaml is

```
steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '${_ENV_PATH}', 'POInvoiceParser/env.yaml']
  - name: gcr.io/cloud-builders/gcloud
    args: ["functions", 'deploy', "invoice-parser", '--entry-point', 'Galenicum.POInvoiceParser.FileParsedHandler', '--runtime', 'dotnet3 ', '--trigger-topic', 'po-invoice-scanned', '--env-vars-file=env.yaml', '--region=europe-west3', '--project=${_TARGET_PROJECT_ID}']
    dir: 'POInvoiceParser'

```
when the build is triggered I'm getting an 'Invalid runtime' error

```
starting build "f31662d0-5a43-4e03-b6b7-03e1206fe7a2"

FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/my-project/r/my-repo
 * branch            a9d93903b4bd87c7441797f4b27d2f3ff2c6774c -> FETCH_HEAD
Updating files:  85% (856/998)
Updating files:  86% (859/998)
Updating files:  87% (869/998)
Updating files:  88% (879/998)
Updating files:  89% (889/998)
Updating files:  90% (899/998)
Updating files:  91% (909/998)
Updating files:  92% (919/998)
Updating files:  93% (929/998)
Updating files:  94% (939/998)
Updating files:  95% (949/998)
Updating files:  96% (959/998)
Updating files:  97% (969/998)
Updating files:  98% (979/998)
Updating files:  99% (989/998)
Updating files: 100% (998/998)
Updating files: 100% (998/998), done.
HEAD is now at a9d9390 chore: seed
BUILD
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #0: Copying gs://environment-variables/po-project/dev/po-invoice-parser-env.yaml...
Step #0: / [0 files][    0.0 B/   31.0 B]                                                
-
- [1 files][   31.0 B/   31.0 B]                                                
Step #0: Operation completed over 1 objects/31.0 B.                                       
Finished Step #0
Starting Step #1
Step #1: Already have image (with digest): gcr.io/cloud-builders/gcloud
Step #1: ERROR: (gcloud.functions.deploy) ResponseError: status=[400], code=[Bad Request], message=[The request has errors
Step #1: Problems:
Step #1: runtime:
Step #1: Invalid runtime.
Step #1: ]
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 1
```

Any clue?
